name: Debug Render Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Debug Files in Templates
        run: ls -l templates/

      - name: Debug Full Directory Structure
        run: tree
