name: Debug Render Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
       
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Check Current Directory
        run: pwd && ls -l

      - name: Debug Files in Templates
        run: ls -l pru_calculator/templates/  

